### ISSUE TITLE
Cannot run your example - ConfigParser.NoSectionError: No section: 'api'

### ISSUE THREAD

**Issue by wolframteetz** [drewfustin/isocronut#1]
Import checks

(...)

> > > import hmac
> > > import base64
> > > import urlparse
> > > import ConfigParser
> > > import simplejson
> > > import urllib2
> > > import time
> > > import datetime
> > > import math
> > > 
> > > import isocronut
> > > origin = '111 W Washington, Chicago'
> > > duration = 10
> > > 
> > > isochrone = isocronut.get_isochrone(origin, duration)
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "isocronut.py", line 325, in get_isochrone
> > >     origin_geocode = geocode_address(origin, access_type, config_path)
> > >   File "isocronut.py", line 170, in geocode_address
> > >     key = config.get('api', 'api_number')
> > >   File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 607, in get
> > >     raise NoSectionError(section)
> > > ConfigParser.NoSectionError: No section: 'api'

Any idea?

unknown0023dffeacbb:isocronut-master sir$ python --version
Python 2.7.10

**Comment by drewfustin** [comment]
With the Python module I wrote, I access these credentials from an external file. If you're so inclined to do the same instead of hard-coding them in, open up your editor of choice and create a file called 'google_maps.cfg' that will contain your API key (or Client ID and Crypto Key, if you are using API for Work). In a folder you have noted and can point the script to (using the config_path variable), make a file that looks just like this (leaving some fields blank, depending on if you are using the Free or Work API), except that it actually has your credentials in it:
'''
[api]
api_number=<YOUR API KEY>
client_id=<YOUR CLIENT ID>
crypto_key=<YOUR CRYPTO KEY>
'''

**Comment by wolframteetz** [comment]
Actually I just figured out I have to put the config file in a "config" subdirectory, that was the reason why it didn't work and I overread that on your website
